version: '3'

services:

  gremlin-server-janus-berkeleyje:
    build:
      context: .
      args:
        JANUSGRAPH_VERSION: 0.3.1
    image: ${DOCKER_NAMESPACE:-localhost:5000}/gremlin-server-janus-berkeleyje:0.3.1-1
